root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/webhooks ."
  bin = "./tmp/webhooks"
  full_bin = "./tmp/webhooks"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  exclude_unchanged = true
  follow_symlink = false
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = false
  main_only = true

[color]
  main = "cyan"
  watcher = "magenta"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
